### ISSUE TITLE
Where do I find "tracer"?

### ISSUE THREAD

**Issue by noomorph** [dxnn/isomorphic-artwork#1]
After watching your talk on JSConf 2015, I got interested in this way of debugging, but I fail to run the last example (with debugging a random JS framework on ToDo MVC), because I cannot find "tracer" you were using in such snippets like this one:

``` javascript
    tracer.trackHits()
    var popup = window.open('http://127.0.0.1/~dann/genart/monitor.html')

    function gogo() {
      var list = tracer.hitCountDeltas(0)
      if(list.length) 
        popup.postMessage(list, "*")
      setTimeout(gogo, 300)
    }
    gogo()

```

Where can I find the aforementioned `tracer`?

Thanks in advance

**Comment by dxnn** [comment]
Hi Yaroslav, sorry for the delay, apparently this notification got lost for a few years. 

The tracer function comes from a package called fondue. It looks like the package.json file didn't make it into the repo -- I've added that now. 

Note that much of this may have bitrotted in the intervening years, so I would be surprised if it didn't take some effort to get things running again! 😄
